name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./path/to/terraform/config

    - name: Format Terraform files
      run: terraform fmt -check
      working-directory: ./path/to/terraform/config

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./path/to/terraform/config